package pl.edu.wat.ml_application.utils

import com.google.firebase.ml.naturallanguage.translate.FirebaseTranslateLanguage

class StaticValues {
    companion object {
        /*var languages: HashMap<Int, String> = hashMapOf(
            //null to "Detect language",
            0 to "Afrikaans"
            1 to "Arabic",
            2 to "Belarusian",
            3 to "Bulgarian",
            4 to "Bengali",
            5 to "Catalan",
            6 to "Czech",
            7 to "Welsh",
            8 to "Danish",
            9 to "German",
            "el" to "Greek",
            "en" to "English",
            "eo" to "Esperanto",
            "es" to "Spanish",
            "et" to "Estonian",
            "fa" to "Persian",
            "fi" to "Finnish",
            "fr" to "French",
            "ga" to "Irish",
            "gl" to "Galician",
            "gu" to "Gujarati",
            "he" to "Hebrew",
            "hi" to "Hindi",
            "hr" to "Croatian",
            "ht" to "Haitian",
            "hu" to "Hungarian",
            "id" to "Indonesian",
            "is" to "Icelandic",
            "it" to "Italian",
            "ja" to "Japanese",
            "ka" to "Georgian",
            "kn" to "Kannada",
            "ko" to "Korean",
            "lt" to "Lithuanian",
            "lv" to "Latvian",
            "mk" to "Macedonian",
            "mr" to "Marathi",
            "ms" to "Malay",
            "mt" to "Maltese",
            "nl" to "Dutch",
            "no" to "Norwegian",
            "pl" to "Polish",
            "pt" to "Portuguese",
            "ro" to "Romanian",
            "ru" to "Russian",
            "sk" to "Slovak",
            "sl" to "Slovenian",
            "sq" to "Albanian",
            "sv" to "Swedish",
            "sw" to "Swahili",
            "ta" to "Tamil",
            "te" to "Telugu",
            "th" to "Thai",
            "tl" to "Tagalog",
            "tr" to "Turkish",
            "uk" to "Ukrainian",
            "ur" to "Urdu",
            "vi" to "Vietnamese",
            "zh" to "Chinese"
        )*/

        var languages: ArrayList<String> = arrayListOf(
            "Afrikaans",
            "Arabic",
            "Belarusian",
            "Bulgarian",
            "Bengali",
            "Catalan",
            "Czech",
            "Welsh",
            "Danish",
            "German",
            "Greek",
            "English",
            "Esperanto",
            "Spanish",
            "Estonian",
            "Persian",
            "Finnish",
            "French",
            "Irish",
            "Galician",
            "Gujarati",
            "Hebrew",
            "Hindi",
            "Croatian",
            "Haitian",
            "Hungarian",
            "Indonesian",
            "Icelandic",
            "Italian",
            "Japanese",
            "Georgian",
            "Kannada",
            "Korean",
            "Lithuanian",
            "Latvian",
            "Macedonian",
            "Marathi",
            "Malay",
            "Maltese",
            "Dutch",
            "Norwegian",
            "Polish",
            "Portuguese",
            "Romanian",
            "Russian",
            "Slovak",
            "Slovenian",
            "Albanian",
            "Swedish",
            "Swahili",
            "Tamil",
            "Telugu",
            "Thai",
            "Tagalog",
            "Turkish",
            "Ukrainian",
            "Urdu",
            "Vietnamese",
            "Chinese"
        )

        const val cameraRequestCode = 1001
        var uri: String = ""
    }
}